"""add card_alert_sender_email and card_last4 columns

Revision ID: 9e7455313af5
Revises: 076054a5d5ae
Create Date: 2026-07-07 21:38:59.667839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7455313af5'
down_revision: Union[str, Sequence[str], None] = '076054a5d5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_accounts', sa.Column('card_last4', sa.String(length=4), nullable=True, comment='クレジットカード番号下4桁（account_type=credit_cardのみ使用。利用速報メール本文からの抽出値との整合性検証用）'))
    op.add_column('m_institutions', sa.Column('card_alert_sender_email', sa.String(), nullable=True, comment='クレジットカード利用速報メールの送信元アドレス（Fromヘッダ。institution_type=credit_cardのみ使用。実メールサンプル確認後に設定）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_institutions', 'card_alert_sender_email')
    op.drop_column('m_accounts', 'card_last4')
    # ### end Alembic commands ###
