"""initial schema

Revision ID: ab52946b0389
Revises: 
Create Date: 2026-07-07 16:29:46.485510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab52946b0389'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_asset_classes',
    sa.Column('id', sa.Integer(), nullable=False, comment='資産クラスID'),
    sa.Column('asset_class_name', sa.String(), nullable=False, comment='資産クラス名（例: 現金、国内株式、投資信託、ローン）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_class_name'),
    comment='資産クラスマスタ'
    )
    op.create_table('m_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='カテゴリID'),
    sa.Column('category_name', sa.String(), nullable=False, comment='カテゴリ名（例: 食費、交通費、給与、未分類）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    comment='カテゴリマスタ（収入・支出どちらの取引にも使う中立的な分類）'
    )
    op.create_table('m_institutions',
    sa.Column('id', sa.Integer(), nullable=False, comment='金融機関ID'),
    sa.Column('institution_name', sa.String(), nullable=False, comment='金融機関名（例: 楽天銀行、三井住友カード）'),
    sa.Column('institution_type', sa.String(), nullable=False, comment='機関種別（bank/credit_card/securities/qr_payment）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='金融機関マスタ'
    )
    op.create_table('t_batch_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='バッチ実行ID'),
    sa.Column('run_date', sa.Date(), nullable=False, comment='実行対象日'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='開始日時'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='終了日時'),
    sa.Column('status', sa.String(), nullable=False, comment='実行結果（success/partial_success/failed）'),
    sa.Column('new_transaction_count', sa.Integer(), nullable=False, comment='新規取込件数'),
    sa.Column('transfer_detected_count', sa.Integer(), nullable=False, comment='振替検知件数'),
    sa.Column('institution_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='機関ごとの成否内訳（JSON配列: 機関名/status/件数またはエラー内容）'),
    sa.Column('error_message', sa.String(), nullable=True, comment='バッチ全体レベルのエラー内容（発生時のみ）'),
    sa.Column('discord_notified_at', sa.DateTime(timezone=True), nullable=True, comment='Discord通知送信日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='日次バッチ実行履歴'
    )
    op.create_table('m_accounts',
    sa.Column('id', sa.Integer(), nullable=False, comment='口座ID'),
    sa.Column('institution_id', sa.Integer(), nullable=False, comment='金融機関ID（m_institutions参照）'),
    sa.Column('account_name', sa.String(), nullable=False, comment='口座表示名（例: 楽天銀行 個人）'),
    sa.Column('account_type', sa.String(), nullable=False, comment='口座種別（bank/credit_card/securities/qr_payment/loan）'),
    sa.Column('is_business', sa.Boolean(), nullable=False, comment='事業用口座フラグ（口座自体の分類）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効フラグ（解約・休眠口座はFALSE。自動取込対象からは外れるが過去データは保持）'),
    sa.Column('default_business_ratio', sa.Numeric(precision=5, scale=2), nullable=False, comment='当口座で新規作成される取引に適用する事業按分デフォルト率(%)'),
    sa.Column('tracks_balance', sa.Boolean(), nullable=False, comment='残高追跡対象フラグ（TRUEの口座のみt_asset_snapshotsを持つ。クレカ・都度引き落とし式QR決済はFALSE）'),
    sa.Column('balance_method', sa.String(), nullable=True, comment='残高算出方式（cumulative=初期残高+取引累積 / moneyforward=MF連携 / manual=手動入力）'),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True, comment='初期残高（balance_method=cumulativeの口座のみ使用）'),
    sa.Column('opening_balance_date', sa.Date(), nullable=True, comment='初期残高の基準日'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['institution_id'], ['m_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='口座マスタ（銀行口座・クレジットカード・証券口座・QR決済アカウント・ローン）'
    )
    op.create_table('m_budgets',
    sa.Column('id', sa.Integer(), nullable=False, comment='予算ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='対象カテゴリID（m_categories参照）'),
    sa.Column('year_month', sa.String(), nullable=False, comment='対象年月（YYYY-MM形式）'),
    sa.Column('is_business', sa.Boolean(), nullable=False, comment='事業予算/個人予算の区分'),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='予算金額'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['category_id'], ['m_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year_month', 'is_business', name='uq_m_budgets_category_month'),
    comment='予算マスタ（カテゴリ×年月×個人/事業区分ごとの予算額）'
    )
    op.create_table('m_category_rules',
    sa.Column('id', sa.Integer(), nullable=False, comment='ルールID'),
    sa.Column('keyword_pattern', sa.String(), nullable=False, comment='摘要とのマッチングに使うキーワード（部分文字列一致）'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='一致時に適用するカテゴリID（m_categories参照）'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='適用優先順位（値が小さいほど優先。最初に一致したルールを採用）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['category_id'], ['m_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='カテゴリ自動分類ルールマスタ（摘要文字列との部分文字列マッチング）'
    )
    op.create_table('t_asset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False, comment='スナップショットID'),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='評価基準日'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='口座ID（m_accounts参照）'),
    sa.Column('asset_class_id', sa.Integer(), nullable=False, comment='資産クラスID（m_asset_classes参照）'),
    sa.Column('ticker_or_name', sa.String(), nullable=False, comment='銘柄コードまたは名称（現金・ローンは口座名をそのまま格納）'),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False, comment='評価額（時価）。ローンはマイナス値'),
    sa.Column('book_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='簿価（取得原価。証券のみ使用）'),
    sa.Column('source_type', sa.String(), nullable=False, comment='取得元（cumulative=初期残高+取引累積/moneyforward=MF連携/manual=手動入力）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['account_id'], ['m_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_class_id'], ['m_asset_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'account_id', 'ticker_or_name', name='uq_t_asset_snapshots_date_account_ticker'),
    comment='資産スナップショット（残高追跡対象口座の日次評価額。ローンはマイナス値で記録）'
    )
    op.create_index('idx_t_asset_snapshots_date', 't_asset_snapshots', ['snapshot_date'], unique=False)
    op.create_table('t_transactions',
    sa.Column('id', sa.Integer(), nullable=False, comment='取引ID'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='口座ID（m_accounts参照）'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='取引日'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='取引金額（支出はマイナス、収入はプラスで統一）'),
    sa.Column('description', sa.String(), nullable=False, comment='摘要'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='カテゴリID（m_categories参照、NULLは未分類）'),
    sa.Column('business_ratio', sa.Numeric(precision=5, scale=2), nullable=False, comment='事業按分比率(%)。0より大きい値が事業取引を意味する（is_businessフラグは持たない）'),
    sa.Column('source_type', sa.String(), nullable=False, comment='取得元種別（gmail_imap/moneyforward_csv/moneyforward_scraping/manual）'),
    sa.Column('source_hash', sa.String(), nullable=False, comment='重複検知用SHA256ハッシュ（account_id+date+amount+description+ソース側一意ID[Message-ID等]から算出）'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='取得した生データ（JSON形式。メールのMessage-ID、カード番号下4桁の検証結果等を含む）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['account_id'], ['m_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['m_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash'),
    comment='取引（各口座・カードの入出金実績）'
    )
    op.create_index('idx_t_transactions_account_id', 't_transactions', ['account_id'], unique=False)
    op.create_index('idx_t_transactions_category_id', 't_transactions', ['category_id'], unique=False)
    op.create_index('idx_t_transactions_date', 't_transactions', ['transaction_date'], unique=False)
    op.create_index('idx_t_transactions_raw_data', 't_transactions', ['raw_data'], unique=False, postgresql_using='gin')
    op.create_table('t_transfers',
    sa.Column('id', sa.Integer(), nullable=False, comment='振替リンクID'),
    sa.Column('from_transaction_id', sa.Integer(), nullable=False, comment='出金側取引ID（t_transactions参照）'),
    sa.Column('to_transaction_id', sa.Integer(), nullable=False, comment='入金側取引ID（t_transactions参照）'),
    sa.Column('match_confidence', sa.String(), nullable=False, comment='検知方式（auto=自動検知/manual=手動紐付け）'),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='紐付け日時'),
    sa.CheckConstraint('from_transaction_id <> to_transaction_id', name='chk_t_transfers_distinct'),
    sa.ForeignKeyConstraint(['from_transaction_id'], ['t_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_transaction_id'], ['t_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_transaction_id'),
    sa.UniqueConstraint('to_transaction_id'),
    comment='口座間振替の相殺リンク（二重計上防止。リンクされた取引は各種集計から除外する）'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_transfers')
    op.drop_index('idx_t_transactions_raw_data', table_name='t_transactions', postgresql_using='gin')
    op.drop_index('idx_t_transactions_date', table_name='t_transactions')
    op.drop_index('idx_t_transactions_category_id', table_name='t_transactions')
    op.drop_index('idx_t_transactions_account_id', table_name='t_transactions')
    op.drop_table('t_transactions')
    op.drop_index('idx_t_asset_snapshots_date', table_name='t_asset_snapshots')
    op.drop_table('t_asset_snapshots')
    op.drop_table('m_category_rules')
    op.drop_table('m_budgets')
    op.drop_table('m_accounts')
    op.drop_table('t_batch_logs')
    op.drop_table('m_institutions')
    op.drop_table('m_categories')
    op.drop_table('m_asset_classes')
    # ### end Alembic commands ###
